export const config = [
  {
    id:0,
    title:'现金红包',
    detail:'每月10元现金红包',
    url:require('../image/member_pic1.png')
  },
  {
    id:1,
    title:'专属提额',
    detail:'10%-20%借款额度提升',
    url:require('../image/member_pic2.png')
  },
  {
    id:2,
    title:'会员专享券',
    detail:'每月价值100元优惠券',
    url:require('../image/member_pic3.png')
  },
  {
    id:3,
    title:'一元购好物',
    detail:'专场商品一元购买',
    url:require('../image/member_pic4.png')
  },
  {
    id:4,
    title:'会员专享价',
    detail:'全场商品最高95折',
    url:require('../image/member_pic5.png')
  },
  {
    id:5,
    title:'生日礼遇',
    detail:'50元无门槛优惠券',
    url:require('../image/member_pic6.png')
  },
  {
    id:6,
    title:'购物免邮',
    detail:'每月4张运费券',
    url:require('../image/member_pic7.png')
  },
  {
    id:7,
    title:'独立成团',
    detail:'直享拼团价',
    url:require('../image/member_pic8.png')
  },
  {
    id:8,
    title:'头像挂件',
    detail:'专属皇冠饰品',
    url:require('../image/member_pic9.png')
  }
]